# Désactive la fonction DNS de dnsmasq
port=0
log-dhcp

# ── LE VRAI POOL DHCP ────────────────────────────────────────────────────────
# On définit la plage d'IP (.20 à .120), le masque de sous-réseau, et le bail (2h)
dhcp-range=10.231.238.121,10.231.238.200,255.255.255.0,2h

# ── OPTIONS RÉSEAU CLASSIQUES ────────────────────────────────────────────────
# Option 3 : La passerelle / routeur par défaut de votre VLAN (à adapter si besoin)
dhcp-option=3,10.231.238.1

# Option 6 : Le serveur DNS pour que les PC aient internet (DNS de la boîte ou Cloudflare)
dhcp-option=6,1.1.1.1,8.8.8.8

# ── LOGIQUE DE BOOT iPXE (ANTI-BOUCLE INFERNALE) ─────────────────────────────
# On détecte si la machine qui demande une IP est déjà sous l'environnement iPXE
# (iPXE envoie l'User-Class "iPXE" ou l'option 175).
dhcp-match=set:is_ipxe,175

# CAS 1 : Le PC boot pour la première fois (PXE standard de la carte mère)
# On lui donne une IP + on lui dit de télécharger "ipxe.efi" via notre TFTP
dhcp-boot=tag:!is_ipxe,ipxe.efi,10.231.238.11

# CAS 2 : Le PC a chargé iPXE et refait sa requête DHCP pour avoir son script
# On lui donne une IP + on le redirige directement vers l'URL HTTP de ton FastAPI
dhcp-boot=tag:is_ipxe,http://10.231.238.11:8000/boot

# ── CONFIGURATION TFTP INTEGRÉ ───────────────────────────────────────────────
enable-tftp
tftp-root=/srv/tftp